# Generated by Django 5.2.7 on 2025-10-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ManyToManyField(blank=True, limit_choices_to={'role': 'developer'}, related_name='project_developer', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('qas', models.ManyToManyField(blank=True, limit_choices_to={'role': 'qa'}, related_name='project_qas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
