# Generated by Django 5.2.7 on 2025-10-03 14:44

import bugs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/', validators=[bugs.models.validate_screenshot])),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
