# Generated by Django 5.2.7 on 2025-10-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('resolved', 'Resolved')], max_length=10),
        ),
    ]
